media:
  input: src/assets
  output: /src/assets
content:
  - name: hero
    format: yaml
    label: Hero content
    path: src/data/heroTest.yaml
    type: file
    fields:
      - name: id
        label: Section name
        type: string
        default: "hero"
        hidden: true
      - name: content
        label: Content
        type: rich-text
        options:
          media: false
      - name: image
        label: Image
        type: image
